name: farmer_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  image_picker: ^0.8.7+3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/BuyerProfile.jpg
    - assets/images/Cucumber.jpg
    - assets/images/leafygreens.jpg
    - assets/images/Tomato.jpg
    - assets/images/wheatImg.jpeg
    - assets/Supplies_Images/corn.webp
    - assets/Supplies_Images/onino.webp
    - assets/Supplies_Images/onion.jpeg
    - assets/Supplies_Images/potato.jpeg
    - assets/Supplies_Images/tomato.jpg
    - assets/Supplies_Images/wheat-grain.jpg
